version: "3.6"

services: 
  mredis:
    image: redis


  mnode:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports: 
      - 8001:8001
    tty: true
    command: bash -c "yarn install && yarn start"
    volumes: 
      - ./:/home/app/web:Z
      - node-modules:/home/app/web/node_modules

volumes: 
  node-modules: